
package pl.basistam.soa.parkingSpaceSensor.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ParkingSensorsService", targetNamespace = "http://webService.main.soa.basistam.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParkingSensorsService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "releaseParkingSpot", targetNamespace = "http://webService.main.soa.basistam.pl/", className = "pl.basistam.soa.parkingSpaceSensor.client.ReleaseParkingSpot")
    @ResponseWrapper(localName = "releaseParkingSpotResponse", targetNamespace = "http://webService.main.soa.basistam.pl/", className = "pl.basistam.soa.parkingSpaceSensor.client.ReleaseParkingSpotResponse")
    @Action(input = "http://webService.main.soa.basistam.pl/ParkingSensorsService/releaseParkingSpotRequest", output = "http://webService.main.soa.basistam.pl/ParkingSensorsService/releaseParkingSpotResponse")
    public boolean releaseParkingSpot(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "takeParkingSpot", targetNamespace = "http://webService.main.soa.basistam.pl/", className = "pl.basistam.soa.parkingSpaceSensor.client.TakeParkingSpot")
    @ResponseWrapper(localName = "takeParkingSpotResponse", targetNamespace = "http://webService.main.soa.basistam.pl/", className = "pl.basistam.soa.parkingSpaceSensor.client.TakeParkingSpotResponse")
    @Action(input = "http://webService.main.soa.basistam.pl/ParkingSensorsService/takeParkingSpotRequest", output = "http://webService.main.soa.basistam.pl/ParkingSensorsService/takeParkingSpotResponse")
    public boolean takeParkingSpot(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
