
package pl.basistam.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatisticsService", targetNamespace = "http://basistam.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatisticsService {


    /**
     * 
     * @param charSequence
     * @return
     *     returns pl.basistam.soa.CharSequenceData
     */
    @WebMethod
    @WebResult(name = "data", targetNamespace = "")
    @RequestWrapper(localName = "analyzeCharSequence", targetNamespace = "http://basistam.pl/", className = "pl.basistam.soa.AnalyzeCharSequence")
    @ResponseWrapper(localName = "analyzeCharSequenceResponse", targetNamespace = "http://basistam.pl/", className = "pl.basistam.soa.AnalyzeCharSequenceResponse")
    @Action(input = "http://basistam.pl/StatisticsService/analyzeCharSequenceRequest", output = "http://basistam.pl/StatisticsService/analyzeCharSequenceResponse")
    public CharSequenceData analyzeCharSequence(
        @WebParam(name = "charSequence", targetNamespace = "")
        String charSequence);

}
