
package pl.basistam.client;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyExchange", targetNamespace = "http://lab9.basistam.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyExchange {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActualCourse", targetNamespace = "http://lab9.basistam.pl/", className = "pl.basistam.client.GetActualCourse")
    @ResponseWrapper(localName = "getActualCourseResponse", targetNamespace = "http://lab9.basistam.pl/", className = "pl.basistam.client.GetActualCourseResponse")
    @Action(input = "http://lab9.basistam.pl/CurrencyExchange/getActualCourseRequest", output = "http://lab9.basistam.pl/CurrencyExchange/getActualCourseResponse")
    public BigDecimal getActualCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertToPln", targetNamespace = "http://lab9.basistam.pl/", className = "pl.basistam.client.ConvertToPln")
    @ResponseWrapper(localName = "convertToPlnResponse", targetNamespace = "http://lab9.basistam.pl/", className = "pl.basistam.client.ConvertToPlnResponse")
    @Action(input = "http://lab9.basistam.pl/CurrencyExchange/convertToPlnRequest", output = "http://lab9.basistam.pl/CurrencyExchange/convertToPlnResponse")
    public BigDecimal convertToPln(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
